import {createCipheriv, createDecipheriv, createHmac, createSecretKey, hkdfSync, randomBytes, timingSafeEqual, type KeyObject} from 'node:crypto';
import {inspect} from 'node:util';

/** Only these codes may cross the boundary around keys. Never attach a raw cause. */
export class SecretError extends Error {
  constructor(readonly code: string) {
    super(code);
    this.name = 'SecretError';
  }
}

export type RecordIdentity = {id: string; user_id: string; provider: string};
export type Sealed = {cipher: Uint8Array; nonce: Uint8Array};

/** Opaque key material: neither JSON nor inspection can expose its derived keys. */
export class SecretKey {
  #enc: KeyObject;
  #kcv: Buffer;

  private constructor(bytes: Buffer) {
    const derive = (info: string) => {
      const derived = Buffer.from(hkdfSync('sha256', bytes, 'quotum/kek/v1', info, 32));
      try { return createSecretKey(derived); } finally { derived.fill(0); }
    };
    this.#enc = derive('enc');
    this.#kcv = createHmac('sha256', derive('check')).update('quotum/kek-check/v1').digest();
  }

  static parse(value: Uint8Array): SecretKey {
    if (value.length !== 43 || !value.every(byte => byte >= 0x21 && byte <= 0x7e)) throw new SecretError('secret_key_invalid');
    const text = Buffer.from(value).toString('ascii');
    if (!/^[A-Za-z0-9_-]{43}$/.test(text)) throw new SecretError('secret_key_invalid');
    const bytes = Buffer.from(text, 'base64url');
    try {
      if (bytes.length !== 32 || bytes.toString('base64url') !== text) throw new SecretError('secret_key_invalid');
      return new SecretKey(bytes);
    } finally { bytes.fill(0); }
  }

  get fingerprint(): string { return this.#kcv.subarray(0, 8).toString('hex'); }
  get checkValue(): string { return this.#kcv.toString('hex'); }
  matches(checkValue: string): boolean {
    return /^[0-9a-f]{64}$/.test(checkValue) && timingSafeEqual(this.#kcv, Buffer.from(checkValue, 'hex'));
  }
  toJSON(): null { return null; }
  [inspect.custom](): string { return '[SecretKey]'; }

  seal(record: RecordIdentity, plaintext: Uint8Array): Sealed {
    try {
      const nonce = randomBytes(12);
      const cipher = createCipheriv('aes-256-gcm', this.#enc, nonce, {authTagLength: 16});
      cipher.setAAD(aad(record));
      return {nonce, cipher: Buffer.concat([cipher.update(plaintext), cipher.final(), cipher.getAuthTag()])};
    } catch { throw new SecretError('credential_failed'); }
  }

  /** Plaintext stays inside the callback and is wiped after use or failure. */
  use<T>(record: RecordIdentity & Sealed, consume: (plaintext: Buffer) => T): T {
    let partial: Buffer | undefined;
    let plaintext: Buffer | undefined;
    try {
      if (!(record.nonce instanceof Uint8Array) || record.nonce.length !== 12 || !(record.cipher instanceof Uint8Array) || record.cipher.length < 16) throw new SecretError('credential_unreadable');
      const cipher = Buffer.from(record.cipher);
      const decipher = createDecipheriv('aes-256-gcm', this.#enc, record.nonce, {authTagLength: 16});
      decipher.setAAD(aad(record));
      decipher.setAuthTag(cipher.subarray(-16));
      partial = decipher.update(cipher.subarray(0, -16));
      plaintext = Buffer.concat([partial, decipher.final()]);
    } catch {
      partial?.fill(0);
      throw new SecretError('credential_unreadable');
    }
    try { return consume(plaintext); } finally { partial?.fill(0); plaintext.fill(0); }
  }
}

function aad(record: RecordIdentity): Buffer {
  // Ids are generated by the hub; provider ids are fixed by connector code.
  if ([record.id, record.user_id, record.provider].some(value => typeof value !== 'string' || /[\r\n\0]/.test(value))) throw new SecretError('credential_unreadable');
  return Buffer.from(`quotum/credential/v1\n${record.id}\n${record.user_id}\n${record.provider}`);
}
